---
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    mem_limit: 256m
    mem_reservation: 128m
    cpus: 0.1
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitor

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    mem_limit: 2g
    mem_reservation: 1g
    cpus: 1
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - monitor

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    mem_limit: 1g
    mem_reservation: 512m
    cpus: 1
    restart: unless-stopped
    environment:
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${GF_AUTH_GENERIC_OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.dimoracosta.it/application/o/authorize/"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.dimoracosta.it/application/o/token/"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.dimoracosta.it/application/o/userinfo/"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.dimoracosta.it/application/o/monitor/end-session/"
      GF_SERVER_ROOT_URL: "https://monitor.dimoracosta.it"
      GF_AUTH_OAUTH_AUTO_LOGIN: "true"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'authentik Admins') && 'Admin' || 'Viewer'"
    networks:
      - traefik
      - monitor
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.grafana.rule=Host(`monitor.dimoracosta.it`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certResolver=cloudflare
      - traefik.http.routers.grafana.middlewares=crowdsec-bouncer@file,ratelimiter@file
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

networks:
  monitor:
    external: true
  traefik:
    external: true

volumes:
  prometheus_data:
  grafana_data:
