---
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
      GID: "${GID-1000}"
    mem_reservation: 128m
    mem_limit: 512m
    cpus: 0.5
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./config/appsec.yaml:/etc/crowdsec/acquis.d/appsec.yaml
      - db:/var/lib/crowdsec/data/
      - config:/etc/crowdsec/
      - traefik_logs:/var/log/traefik:ro
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true

volumes:
  db:
  config:
  traefik_logs:
    external: true